version: "3.8"
services: 
  database:
    image: "mongo"
    volumes:
      - data:/data/db

  backend:
    build: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - database
    
      
  frontend: 
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src 
    depends_on:
      - backend
    stdin_open: true
    tty: true
    

volumes:
  data: